In [94]:
#### Задание 1.1

In [2]:
import numpy as np


In [3]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23])

In [4]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [5]:
b = np.array([i+12 for i in range(12)])

In [6]:
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
a = np.arange(12,24)


In [8]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [9]:
#### Создать 5 двумерных массивов разной формы из массива a.
#### Не использовать в аргументах метода reshape число -1.

In [10]:
a = np.array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
a


array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [12]:
a = a.reshape(6,10)

In [13]:
a

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
a = a.reshape(10,6)

In [15]:
a

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
a = a.reshape(5,12)

In [17]:
a

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
#### Создать 5 двумерных массивов разной формы из массива a.
#### Использовать в аргументах метода reshape число -1
#### (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [19]:
a =  a.reshape(5,-1)


In [20]:
a 

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
b =  a.reshape(-1,12)

In [22]:
b

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [23]:
b = a.reshape(-5,12)

In [24]:
b

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [25]:
b = a.reshape(-12,5)

In [26]:
b


array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23]])

In [27]:
b = a.reshape(6,-1)

In [28]:
b


array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
b = np.ones((5,5))*0

In [30]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
#### Задание 1.2

In [32]:
####  Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой:

In [33]:
a = np.random.sample((3,4))

In [34]:
a

array([[0.03772992, 0.32332327, 0.50926692, 0.73688547],
       [0.82386115, 0.43661546, 0.62156738, 0.84075469],
       [0.09686387, 0.74325679, 0.30242183, 0.90087962]])

In [35]:
####  Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
####  из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 

In [36]:
a = np.random.randn(3,4)

In [37]:
a

array([[ 0.08640712, -1.53671664, -1.17633002,  0.20334385],
       [-0.85909715, -0.28855269,  0.44216151, -1.28640773],
       [-1.48209016,  0.3124122 ,  0.41719248,  0.79427274]])

In [38]:
#### Получить из этого массива одномерный массив с таким же атрибутом size, 
#### как и исходный массив.

In [39]:
a = a.flatten()

In [40]:
a


array([ 0.08640712, -1.53671664, -1.17633002,  0.20334385, -0.85909715,
       -0.28855269,  0.44216151, -1.28640773, -1.48209016,  0.3124122 ,
        0.41719248,  0.79427274])

In [41]:
#### 1.3 Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 

In [42]:
a =np.arange(-20,0)*-1


In [43]:
a

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [44]:
a =np.arange(20,0,-1)

In [45]:
a

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [46]:
b =  a.reshape(20,-1)

In [47]:
b

array([[20],
       [19],
       [18],
       [17],
       [16],
       [15],
       [14],
       [13],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1]])

In [56]:
ar3 = np.arange(-20, 0, 2)*-1
print(ar3)

[20 18 16 14 12 10  8  6  4  2]


In [58]:
b = ar3.reshape(10,-1)
print(b)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]
