In [1]:
import numpy as np

In [2]:
a = np.arange(12,24)

In [3]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3 Задание

In [8]:
a.reshape((2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape((6,-1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape((-1,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Узнаем размерность массива: ndim

In [13]:
a.ndim

1

In [14]:
b = a.reshape(12,1)

In [15]:
b.ndim

2

5 задание

a = np.random.randn(3,4)

In [16]:
a = np.random.randn(3,4)
a.mean()

-0.11191625278002792

In [17]:
b = a.flatten()
b

array([-0.01719711, -0.03816546, -1.99964072, -0.53443174,  1.69938564,
       -0.68095144,  1.31192972,  0.03228626,  0.01025211,  0.09612511,
       -0.37009823, -0.85248918])

In [18]:
b.ndim

1

In [19]:
a.size

12

In [20]:
b.size

12

In [21]:
a.size == b.size

True

6 Задание. 10:58

In [24]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [25]:
b = np.arange(20,1,-2).reshape(1,10)


После трансформации получена одна строка и 10 столбцов:

In [28]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [29]:
a.shape

(10,)

In [30]:
b.shape

(1, 10)

In [31]:
a.ndim

1

In [32]:
b.ndim

2

7 Задание:

In [36]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [37]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Создаем новый массив, подставляя вертикально к массиву "а", массив "в" с помощью функции vstack.

In [39]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Либо с помощью функции numpy concatinate. 
axis = 0 это строки, если 
axis = 1 это столбцы.

In [46]:
v = np.concatenate((a,b),axis = 0 )
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Трансформировали его в массив с 4-мя
наблюдениями и 3-мя признаками

Далее транспонируем его с помощью Т. И получаем 3-и наблюдения и 4-признака.

In [52]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

Умножение матриц: 

In [57]:
B = np.dot(A, At)
B


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [58]:
print(A.dot(At),"\n",B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Ищем детерминанту:

In [63]:
np.linalg.det(B)

0.0

Обратную матрцу построить невозможно,
так как детерминант равен 0.

Далее инициализируем генератор случайных чисел:

In [67]:
np.random.seed(42)
c = np.random.randint(0,16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [69]:
C= c.reshape(4,4)
C


array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

Складываем масивы:

In [71]:
D = B + C
D

array([[ 11,  17,  35,  46],
       [ 24,  57,  98, 126],
       [ 29,  95, 151, 218],
       [ 42, 132, 219, 306]])

Ищем детерминант:

In [73]:
np.linalg.det(D)

-47196.0

Ищем ранк матрицы(т.е. у нас четыре линейно независимых столбца и строки, независящих друг от друга):

In [76]:
np.linalg.matrix_rank(D)

4

Находим обратную матрицу:

In [78]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.13488431,  0.07958302,  0.17988813, -0.1812018 ],
       [-0.17149758,  0.14009662,  0.147343  , -0.13687601],
       [-0.05758963,  0.01220442, -0.20404272,  0.14899568],
       [ 0.09668192, -0.08009153,  0.05778032, -0.0194508 ]])

10 - е задание:

In [79]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [80]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [81]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [82]:
E = np.where(D_inv,B,C)
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])